#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs none /dev

cat <<!


Terminate Execution: Ctrl+a x
Enter Monitor Mode: Ctrl+a c


!

exec /bin/sh
