	mov	$'H',	%al
	out	%al,	$0x01
	mov	$'e',	%al
	out	%al,	$0x01
	mov	$'l',	%al
	out	%al,	$0x01
	mov	$'l',	%al
	out	%al,	$0x01
	mov	$'o',	%al
	out	%al,	$0x01
	mov	$',',	%al
	out	%al,	$0x01
	mov	$' ',	%al
	out	%al,	$0x01
	mov	$'W',	%al
	out	%al,	$0x01
	mov	$'o',	%al
	out	%al,	$0x01
	mov	$'r',	%al
	out	%al,	$0x01
	mov	$'l',	%al
	out	%al,	$0x01
	mov	$'d',	%al
	out	%al,	$0x01
	mov	$'!',	%al
	out	%al,	$0x01
	hlt
